#!/bin/sh

if test $# -lt 1
then
    echo "specify a file"
    exit 2
fi

if test ! -f $1
then
cat <<!  > $1
package main

import (
	"flag"
	"os"

	svg "github.com/gmlewis/ponoko2d"
)

var (
	width  = flag.Int("width", 500, "Width of svg")
	height = flag.Int("height", 500, "Height of svg")
	canvas = svg.New(os.Stdout)
)

func background(v int) { canvas.Rect(0, 0, *width, *height, canvas.RGB(v, v, v)) }

func main() {
	canvas.Start(*width, *height)
	background(255)

	// your code here

	canvas.Grid(0, 0, *width, *height, 10, "stroke:black;opacity:0.1")
	canvas.End()
}
!
fi
$EDITOR $1
